### ISSUE TITLE
Match processing of `--optimization-passes 0`

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/cargo-contract#1154]
If a user runs with `--optimization-passes 0` (i.e. `./cargo-contract contract build --workspace --unstable-options original-manifest --optimization-passes 0 --output-json`) like I just did, then when it tries to run `match optimization_passes` here https://github.com/paritytech/cargo-contract/blob/master/crates/build/src/lib.rs#L686, it runs the branch `Some(opt_passes)`, but i think it should instead run the `None` branch (same as if you didn't provide that option at all)... although i may be mistaken...

**Comment by ascjones** [comment]
The `None` branch will first try and read the value provided in the manifest, otherwise will use the [default `Z`](https://github.com/paritytech/cargo-contract/blob/b717ae6d01f2f45978840e0211bc2c2ad828ae68/crates/build/src/wasm_opt.rs#L103).

If the user supplies `--optimization-passes 0` for whatever reason, then it should be used faithfully as if running `wasm-opt` directly.
