### ISSUE TITLE
Rename `metadata.json` to `{contract_name}.json`

### ISSUE THREAD

**Issue by athei** [paritytech/cargo-contract#950]
I don't think it makes sense to name the `contract` and `wasm` file after the contract but not the metadata file. It is just annoying to not be able to see from the file name which contract it belongs to.

**Comment by kvinwang** [comment]
Bundled apps running on modern platforms often come with a manifest file, `AndroidManifest.xml` for Android apps for example.
So, I think the `matadata.json` for ink plays the same role. It is more friendly for external tools to have a static name. We have tools to read the contract name from the metadata.json.

**Comment by ascjones** [comment]
> Bundled apps running on modern platforms often come with a manifest file, `AndroidManifest.xml` for Android apps for example. So, I think the `matadata.json` for ink plays the same role. It is more friendly for external tools to have a static name. We have tools to read the contract name from the metadata.json.

I'm sympathetic to this requirement, we don't want to introduce breaking changes unnecessarily. 

> I don't think it makes sense to name the contract and wasm file after the contract but not the metadata file. It is just annoying to not be able to see from the file name which contract it belongs to.

In some ways we have the best of both worlds at the moment, because the `mycontractname.contract` bundle is just `metadata.json` with the code embedded. It is a legacy thing for sure, but we should think carefully before breaking things and have a very strong reason to do so.

**Comment by SkymanOne** [comment]
I agree with @kvinwang analogy with `AndroidManifest.xml`. There are services that take statically read the manifest files.

**Comment by athei** [comment]
I can't help but thinking of:
https://xkcd.com/1172/

Should we name the other artefacts to static names, too? I am just wondering why it seems to be okay for them but not for the json file.

**Comment by ascjones** [comment]
> Should we name the other artefacts to static names, too? I am just wondering why it seems to be okay for them but not for the json file.

No reason other than the legacy issue of `metadata.json`. Arguably it is a generated artefact rather than a manifest, and as such it is logical for it to have the name of the source.

My reasoning was purely that it is a breaking change, and we should at least think about it before doing it, as we are doing here.

Having thought about it, this is a major release `2.0.0`, so this is a good place to do such a breaking change. Downstream clients which expect `metadata.json` can just assume that any `*.json` file is contract metadata file.

**Comment by athei** [comment]
Exactly. This is the most trivial breaking change you can imagine. If we can't do this in a major release we are not able to change anything. Sorry @kvinwang. I know when stuff breaks this is annoying. But I think this will be the least of your problems when migrating to the new ink! version :)
